
package com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.views.panels;

import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.dto.ClientDTO;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.dto.HistoricalPlanDTO;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.dto.PlanDTO;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.mappers.ClientMapper;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.model.Client;

import java.util.*;
import java.util.stream.Collectors;

import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.model.HistoricalPlan;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.service.ClientService;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.service.HistoricalPlanService;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.service.PlanService;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.utils.PromptSupport;
import org.springframework.stereotype.Component;

import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

@Component
public class HistoricalPanel extends javax.swing.JPanel {

    private DefaultTableModel tableModelHistorical;
    private final ClientService clientService;
    private final PlanService planService;
    private final HistoricalPlanService historicalPlanService;
    private Border defaultBorder;

    public HistoricalPanel(ClientService clientService, PlanService planService, HistoricalPlanService historicalPlanService) {
        this.clientService = clientService;
        this.planService = planService;
        this.historicalPlanService = historicalPlanService;
        initComponents();
        initHistoricalPlanTable();
        loadPlansToComboBox();
    }

    private void initHistoricalPlanTable() {
        tableModelHistorical = new DefaultTableModel();
        tableListClients.setModel(tableModelHistorical);
        // Definir cabeceras de la tabla
        tableModelHistorical.setColumnIdentifiers(new Object[]{
                "Id", "Inicio", "Fin", "Estado", "Cliente", "Plan"
        });
        loadHistoricalPlanToTable(clientService.findAll());
    }

    /**
     * Carga la lista de clientes en la tabla.
     */
    private void loadHistoricalPlanToTable(List<Client> clients) {
        //Clientes desde el service
        tableModelHistorical.setRowCount(0);
        List<HistoricalPlanDTO> historicalPlanDTOS = clients.stream()
                .flatMap(client -> historicalPlanService
                        .findByClientWithDetails(client.getDocumentId().toString()).stream())
                .toList();


        for (HistoricalPlanDTO dto : historicalPlanDTOS) {
            tableModelHistorical.addRow(new Object[] {
                    dto.getIdHistorical(),
                    dto.getStartDate(),
                    dto.getEndDate(),
                    dto.getIsActive(),
                    dto.getClientName(),
                    dto.getPlanName()
            });
        }
    }

    /**
     * Carga todos los planes disponibles en el comboBox.
     * El primer ítem es un texto fijo obligatorio.
     */
    private void loadPlansToComboBox() {
        comboBoxPlan.removeAllItems();
        comboBoxPlan.addItem("Seleccione un Plan *");

        List<PlanDTO> planes = planService.findByIsActiveDTO(true);
        if (planes != null) {
            for (PlanDTO plan : planes) {
                comboBoxPlan.addItem(plan.toString());
            }
        }
    }

    private void resetForm() {
        PromptSupport.setPrompt("Ingrese el DNI *", txtDni);
        PromptSupport.setPrompt("Ingrese el nombre *", txtName);
        PromptSupport.setPrompt("Ingrese el apellido *", txtLastName);
        PromptSupport.setPrompt("Ingrese el mail", txtMail);
        PromptSupport.setPrompt("Ingrese el celular", txtPhone);
        comboBoxPlan.setSelectedIndex(0);
        titleCharge.setText("Nuevo Cliente");
        txtDni.setBorder(defaultBorder);
        txtName.setBorder(defaultBorder);
        txtLastName.setBorder(defaultBorder);
        txtMail.setBorder(defaultBorder);
        txtPhone.setBorder(defaultBorder);
        comboBoxPlan.setBorder(defaultBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        labelMail = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        titleMain = new javax.swing.JLabel();
        panelNewClient = new javax.swing.JPanel();
        titleCharge = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        labelLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        labelDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        labelPlan = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnCleanPanels = new javax.swing.JButton();
        comboBoxPlan = new javax.swing.JComboBox<>();
        btnClientActive = new javax.swing.JRadioButton();
        btnClientInactive = new javax.swing.JRadioButton();
        titleClient = new javax.swing.JLabel();
        titlePlan = new javax.swing.JLabel();
        btnPlanActive = new javax.swing.JRadioButton();
        btnPlanInactive = new javax.swing.JRadioButton();
        labelPhone1 = new javax.swing.JLabel();
        txtPhone1 = new javax.swing.JTextField();
        btnName = new javax.swing.JRadioButton();
        btnLastName = new javax.swing.JRadioButton();
        btnDni = new javax.swing.JRadioButton();
        btnPhone = new javax.swing.JRadioButton();
        btnPlan = new javax.swing.JRadioButton();
        panelTable = new javax.swing.JPanel();
        scrollPaneTable = new javax.swing.JScrollPane();
        tableListClients = new javax.swing.JTable();
        titleList = new javax.swing.JLabel();
        btnSelect = new javax.swing.JButton();
        btnCleanTable = new javax.swing.JButton();

        txtMail.setText("Ingrese el mail");

        txtPhone.setText("Ingrese el celular");

        labelPhone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPhone.setText("Celular");

        labelMail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMail.setText("Mail");

        jRadioButton7.setText("Usar");

        jRadioButton9.setText("Usar");

        setBackground(new java.awt.Color(120, 120, 120));
        setMinimumSize(new java.awt.Dimension(749, 580));

        titleMain.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleMain.setText("Historial");

        titleCharge.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleCharge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleCharge.setText("Busqueda");

        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Nombre");

        txtName.setText("Ingrese el nombre *");

        labelLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLastName.setText("Apellido");

        txtLastName.setText("Ingrese el apellido *");

        labelDni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDni.setText("DNI");

        txtDni.setText("Ingrese el DNI *");

        labelPlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPlan.setText("Seleccione el plan");

        btnSearch.setText("Buscar");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnCleanPanels.setText("Limpiar");
        btnCleanPanels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanPanelsActionPerformed(evt);
            }
        });

        comboBoxPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnClientActive.setText("Activo");

        btnClientInactive.setText("Inactivo");

        titleClient.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titleClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleClient.setText("Por Cliente");

        titlePlan.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titlePlan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlePlan.setText("Por Plan");

        btnPlanActive.setText("Activo");

        btnPlanInactive.setText("Inactivo");

        labelPhone1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPhone1.setText("Celular");

        txtPhone1.setText("Ingrese el celular");

        btnName.setText("Usar");

        btnLastName.setText("Usar");

        btnDni.setText("Usar");

        btnPhone.setText("Usar");

        btnPlan.setText("Usar");

        javax.swing.GroupLayout panelNewClientLayout = new javax.swing.GroupLayout(panelNewClient);
        panelNewClient.setLayout(panelNewClientLayout);
        panelNewClientLayout.setHorizontalGroup(
            panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewClientLayout.createSequentialGroup()
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewClientLayout.createSequentialGroup()
                        .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNewClientLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClientActive))
                            .addGroup(panelNewClientLayout.createSequentialGroup()
                                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelNewClientLayout.createSequentialGroup()
                                .addComponent(btnClientInactive)
                                .addGap(34, 34, 34))
                            .addComponent(btnName, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(panelNewClientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewClientLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCleanPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(titleCharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxPlan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPhone1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelNewClientLayout.createSequentialGroup()
                                .addComponent(labelPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPlan))
                            .addGroup(panelNewClientLayout.createSequentialGroup()
                                .addComponent(labelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLastName))
                            .addGroup(panelNewClientLayout.createSequentialGroup()
                                .addComponent(labelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDni))
                            .addGroup(panelNewClientLayout.createSequentialGroup()
                                .addComponent(labelPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPhone))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNewClientLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnPlanActive)
                                .addGap(18, 18, 18)
                                .addComponent(btnPlanInactive)
                                .addGap(36, 36, 36))
                            .addComponent(titlePlan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelNewClientLayout.setVerticalGroup(
            panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNewClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientActive)
                    .addComponent(btnClientInactive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelName)
                    .addComponent(btnName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLastName)
                    .addComponent(btnLastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDni)
                    .addComponent(btnDni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPhone1)
                    .addComponent(btnPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPhone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlePlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlanActive)
                    .addComponent(btnPlanInactive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPlan)
                    .addComponent(btnPlan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(panelNewClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        tableListClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollPaneTable.setViewportView(tableListClients);

        titleList.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleList.setText("Resultados");

        btnSelect.setText("Seleccionar");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnCleanTable.setText("Limpiar");
        btnCleanTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(titleList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE))
                .addGap(185, 185, 185))
            .addGroup(panelTableLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnCleanTable, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanTable, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelNewClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titleMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleMain)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNewClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        Set<Client> clients = new HashSet<>();

        // Buscar por nombreB
        if (btnName.isSelected()) {
            String name = txtName.getText().trim();
            if (!name.isEmpty() && !name.equals("Ingrese el nombre *")) {
                clients.addAll(clientService.findByName(name));
            }
        }

        // Buscar por apellido
        if (btnLastName.isSelected()) {
            String lastName = txtLastName.getText().trim();
            if (!lastName.isEmpty() && !lastName.equals("Ingrese el apellido *")) {
                clients.addAll(clientService.findByLastName(lastName));
            }
        }

        // Buscar por DNI
        if (btnDni.isSelected()) {
            String dniText = txtDni.getText().trim();
            if (!dniText.isEmpty() && !dniText.equals("Ingrese el DNI *")) {
                try {
                    int dni = Integer.parseInt(dniText);
                    clientService.findById(dni).ifPresent(clients::add);
                } catch (NumberFormatException ignored) {
                    // Mostrar mensaje
                }
            }
        }

        // Buscar por plan
        if (btnPlan.isSelected()) {
            if (comboBoxPlan.getSelectedIndex() != 0) {
                String selectedPlan = comboBoxPlan.getSelectedItem().toString();
                clients.addAll(clientService.findByCurrentPlan(selectedPlan));
            }
        }

        // Mostrar resultados
        titleList.setText("Lista de Historial: Buscados");

        loadHistoricalPlanToTable(new ArrayList<>(clients));
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCleanPanelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanPanelsActionPerformed
        resetForm();
    }//GEN-LAST:event_btnCleanPanelsActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        titleList.setText("Lista de Clientes");
        loadHistoricalPlanToTable(clientService.findAll());
    }//GEN-LAST:event_btnSelectActionPerformed

    private void btnCleanTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanPanels;
    private javax.swing.JButton btnCleanTable;
    private javax.swing.JRadioButton btnClientActive;
    private javax.swing.JRadioButton btnClientInactive;
    private javax.swing.JRadioButton btnDni;
    private javax.swing.JRadioButton btnLastName;
    private javax.swing.JRadioButton btnName;
    private javax.swing.JRadioButton btnPhone;
    private javax.swing.JRadioButton btnPlan;
    private javax.swing.JRadioButton btnPlanActive;
    private javax.swing.JRadioButton btnPlanInactive;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JComboBox<String> comboBoxPlan;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelMail;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelPhone1;
    private javax.swing.JLabel labelPlan;
    private javax.swing.JPanel panelNewClient;
    private javax.swing.JPanel panelTable;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JTable tableListClients;
    private javax.swing.JLabel titleCharge;
    private javax.swing.JLabel titleClient;
    private javax.swing.JLabel titleList;
    private javax.swing.JLabel titleMain;
    private javax.swing.JLabel titlePlan;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPhone1;
    // End of variables declaration//GEN-END:variables
}
