
package com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.views;

import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.repository.HistoricalPlanRepository;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.service.HistoricalPlanService;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.service.PlanService;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.validations.ClientValidation;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.validations.PlanValidation;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.views.panels.ClientPanel;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.views.panels.MainPanel;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.service.ClientService;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.views.panels.PlansPanel;
import com.chicharronSoftware.CRMGYM.fase2.swing.spring.boot.views.panels.HistoricalPanel;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.intellijthemes.FlatDraculaIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;
import java.awt.BorderLayout;
import java.awt.Window;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class Dashboard extends javax.swing.JFrame {
    private final ClientService clientService;
    private final PlanService planService;
    private final HistoricalPlanService historicalPlanService;

    @Autowired
    private PlanValidation planValidation;
    @Autowired
    private ClientValidation clientValidation;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());


    @Autowired
    public Dashboard(ClientService clientService, PlanService planService, HistoricalPlanService historicalPlanService) {
        this.clientService = clientService;
        this.planService = planService;
        this.historicalPlanService = historicalPlanService;
        initComponents();
        jLMessage.putClientProperty("FlatLaf.styleClass", "h1");
        jLDay.putClientProperty("FlatLaf.style", "font: 140% $light.font");
        setDate();
        initContent();
        

    }
    
    private void initContent() {
        MainPanel mp = new MainPanel();
        mp.setSize(1080, 720);
        mp.setLocation(0, 0);

        jPContent.removeAll();
        jPContent.add(mp, BorderLayout.CENTER);
        jPContent.revalidate();
        jPContent.repaint();
    }

    private void setDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        jLDay.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPBackground = new javax.swing.JPanel();
        jPMenues = new javax.swing.JPanel();
        jBClients = new javax.swing.JButton();
        jBMain = new javax.swing.JButton();
        jBHistory = new javax.swing.JButton();
        jBPlans = new javax.swing.JButton();
        jBPay1 = new javax.swing.JButton();
        jLTitle = new javax.swing.JLabel();
        jPContent = new javax.swing.JPanel();
        jPHeader = new javax.swing.JPanel();
        jLMessage = new javax.swing.JLabel();
        jLDay = new javax.swing.JLabel();
        btnDarMode = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));

        jPBackground.setPreferredSize(new java.awt.Dimension(1080, 720));

        jPMenues.setBackground(new java.awt.Color(51, 51, 51));

        jBClients.setText("CLIENTES");
        jBClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClientsActionPerformed(evt);
            }
        });

        jBMain.setText("PRINCIPAL");
        jBMain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMainActionPerformed(evt);
            }
        });

        jBHistory.setText("HISTORIAL");
        jBHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHistoryActionPerformed(evt);
            }
        });

        jBPlans.setText("PLANES");
        jBPlans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBPlans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPlansActionPerformed(evt);
            }
        });

        jBPay1.setText("PAGOS");
        jBPay1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitle.setText("CRMGYM - Fase 2");

        javax.swing.GroupLayout jPMenuesLayout = new javax.swing.GroupLayout(jPMenues);
        jPMenues.setLayout(jPMenuesLayout);
        jPMenuesLayout.setHorizontalGroup(
            jPMenuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPMenuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBClients, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPlans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBPay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMenuesLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPMenuesLayout.setVerticalGroup(
            jPMenuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuesLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLTitle)
                .addGap(68, 68, 68)
                .addComponent(jBMain, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBClients, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBPlans, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBPay1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jPContent.setBackground(new java.awt.Color(204, 204, 204));
        jPContent.setPreferredSize(new java.awt.Dimension(750, 585));
        jPContent.setLayout(new java.awt.BorderLayout());

        jPHeader.setBackground(new java.awt.Color(102, 102, 102));

        jLMessage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLMessage.setText("Hoy es un buen día para entrenar!!!");

        javax.swing.GroupLayout jPHeaderLayout = new javax.swing.GroupLayout(jPHeader);
        jPHeader.setLayout(jPHeaderLayout);
        jPHeaderLayout.setHorizontalGroup(
            jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPHeaderLayout.setVerticalGroup(
            jPHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPHeaderLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLMessage)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLDay.setText("Hoy es Domingo 20 de Julio de 2025");

        btnDarMode.setText("Modo Oscuro");
        btnDarMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBackgroundLayout = new javax.swing.GroupLayout(jPBackground);
        jPBackground.setLayout(jPBackgroundLayout);
        jPBackgroundLayout.setHorizontalGroup(
            jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackgroundLayout.createSequentialGroup()
                .addComponent(jPMenues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPBackgroundLayout.createSequentialGroup()
                        .addComponent(jLDay, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDarMode))
                    .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPBackgroundLayout.setVerticalGroup(
            jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBackgroundLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDarMode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPMenues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMainActionPerformed
        initContent();
    }//GEN-LAST:event_jBMainActionPerformed

    private void jBHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHistoryActionPerformed
        HistoricalPanel hp = new HistoricalPanel(clientService, planService, historicalPlanService);
        hp.setSize(750, 585);
        hp.setLocation(0, 0);

        jPContent.removeAll();
        jPContent.add(hp, BorderLayout.CENTER);
        jPContent.revalidate();
        jPContent.repaint();
    }//GEN-LAST:event_jBHistoryActionPerformed

    //Metodo para llamar a menu cliente
    private void jBClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClientsActionPerformed
        ClientPanel cp = new ClientPanel(clientService, planService, clientValidation);

        cp.setSize(750, 585);
        cp.setLocation(0, 0);

        jPContent.removeAll();
        jPContent.add(cp, BorderLayout.CENTER);
        jPContent.revalidate();
        jPContent.repaint();
        
    }//GEN-LAST:event_jBClientsActionPerformed

    private void jBPlansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPlansActionPerformed
        PlansPanel pp = new PlansPanel(planService, planValidation, clientService);

        pp.setSize(750, 585);
        pp.setLocation(0, 0);

        jPContent.removeAll();
        jPContent.add(pp, BorderLayout.CENTER);
        jPContent.revalidate();
        jPContent.repaint();
        
    }//GEN-LAST:event_jBPlansActionPerformed

    private void btnDarModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarModeActionPerformed
        boolean darkMode = btnDarMode.isSelected();
        setTheme(darkMode);
    }//GEN-LAST:event_btnDarModeActionPerformed

    private void setTheme(boolean darkMode) {
    try {
        if (darkMode) {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.intellijthemes.FlatDraculaIJTheme());
        } else {
            UIManager.setLookAndFeel(new com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme());
        }
        // Refrescar UI de todos los componentes abiertos
        for (Window window : Window.getWindows()) {
            SwingUtilities.updateComponentTreeUI(window);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnDarMode;
    private javax.swing.JButton jBClients;
    private javax.swing.JButton jBHistory;
    private javax.swing.JButton jBMain;
    private javax.swing.JButton jBPay1;
    private javax.swing.JButton jBPlans;
    private javax.swing.JLabel jLDay;
    private javax.swing.JLabel jLMessage;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JPanel jPBackground;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHeader;
    private javax.swing.JPanel jPMenues;
    // End of variables declaration//GEN-END:variables
}
