name: Java CI con Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Levanta un contenedor con MySQL para que las pruebas de Spring Boot puedan conectarse
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: crmgym_fase2
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
          MYSQL_ROOT_PASSWORD: admin_root_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    # Usamos xvfb-run (X Virtual Framebuffer) para emular una pantalla gráfica
    # ya que al inicializar los componentes Swing en el Runner sin interfaz gráfica
    # se podría lanzar una excepción java.awt.HeadlessException.
    - name: Compilar y Probar con Maven
      run: xvfb-run mvn -B clean package
